version: 2

models:
  - name: int_yelp_business
    description: "Intermediate layer for yelp_business table"
    columns:
      - name: business_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: name
        description: "The name for each business_id"
        tests:
          - not_null

  - name: int_yelp_review
    description: "Intermediate layer for yelp_review table"
    columns:
      - name: review_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "The user_id who left the review"
        tests:
          - not_null
      - name: business_id
        description: "The business_id where the user reviewed"
        tests:
          - not_null
